const data = {
  products: [
    {
      name: 'cool mouse',
      slug: 'a mouse',
      category: '2hou',
      image: '/images/p1.png',
      price: 420,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality mouse',
    },
    {
      name: 'padoru mouse',
      slug: 'b mouse',
      category: '2hou',
      image: '/images/p2.png',
      price: 69,
      countInStock: 10,
      brand: '2hou',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'nezuko',
      slug: 'nezuko figurine',
      category: 'standing figure',
      image: '/images/p3.jpg',
      price: 1000,
      countInStock: 4,
      brand: 'bandai namco',
      rating: 4.0,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'sephiroth',
      slug: 'sephiroth figurine',
      category: 'standing figure',
      image: '/images/p4.jpg',
      price: 6900,
      countInStock: 10,
      brand: 'mako',
      rating: 5,
      numReviews: 30,
      description: 'high quality product',
    },
  ],
};
export default data;
