const data = {
  products: [
    {
      // _id: '1',
      name: 'cool mouse',
      slug: 'a mouse',
      image: '/images/p1.png',
      brand: 'Nike',
      category: '2hou',
      description: 'high quality mouse',
      price: 420,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
    },
    {
      //_id: '2',
      name: 'midoriya',
      slug: 'midoriya figurine',
      image: '/images/p2.png',
      brand: '2hou',
      category: 'standing figure',
      description: 'high quality product',
      price: 100,
      countInStock: 10,
      rating: 5,
      numReviews: 10,
    },
    {
      //_id: '3',
      name: 'nezuko',
      slug: 'nezuko figurine',
      image: '/images/p3.jpg',
      brand: 'bandai namco',
      category: 'standing figure',
      description: 'high quality product',
      price: 120,
      countInStock: 4,
      rating: 4.0,
      numReviews: 15,
    },
    {
      //_id: '4',
      name: 'sephiroth',
      slug: 'sephiroth figurine',
      image: '/images/p4.jpg',
      brand: 'mako',
      category: 'standing figure',
      description: 'high quality product',
      price: 690,
      countInStock: 10,
      rating: 5,
      numReviews: 30,
    },
  ],
};
export default data;
