import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Henley White Shirt',
      slug: 'Henley Short Sleeve Shirt',
      image: '/images/p1.png',
      brand: 'Henley',
      category: 'Shirt',
      description:
        'Traditional styling comes into its own with this classic Elder Henley Shirt made from 1x1 rib 100% organic cotton.\nShort sleeves and a three-button neck opening give this shirt an authentic Henley aesthetic.',
      price: 70,
      countInStock: 0,
      rating: 4.5,
      numReviews: 40,
    },
    {
      //_id: '2',
      name: 'Casual Blue Shirt',
      slug: 'Regular Fit Solid Spread Collar Casual Shirt',
      image: '/images/p2.png',
      brand: 'VeBNoR',
      category: 'Shirt',
      description:
        'Style That Speaks Volumes \nThis shirt boasts a modern yet classic design that seamlessly bridges the gap between casual and sophisticated.',
      price: 200,
      countInStock: 10,
      rating: 5,
      numReviews: 10,
    },
    {
      //_id: '3',
      name: 'Black Shirt',
      slug: 'Black Short Sleeve Cotton T-Shirt ',
      image: '/images/p3.png',
      brand: 'STUDIO',
      category: 'Shirt',
      description: 'high quality product',
      price: 120,
      countInStock: 4,
      rating: 4.0,
      numReviews: 15,
    },
    {
      //_id: '4',
      name: 'Blue Shirt',
      slug: 'Blue Short Sleeve Cotton T-Shirt',
      image: '/images/p4.png',
      brand: 'STUDIO',
      category: 'Shirt',
      description: 'high quality product',
      price: 90,
      countInStock: 10,
      rating: 5,
      numReviews: 30,
    },
    {
      //_id: '5',
      name: 'T1 WERKPANT',
      slug: 'T1 WERKPANT',
      image: '/images/p5.png',
      brand: 'TrueWerk',
      category: 'Pant',
      description:
        'Featuring superior comfort and stretch in a lightweight softshell package.',
      price: 50,
      countInStock: 10,
      rating: 5,
      numReviews: 30,
    },
    {
      //_id: '6',
      name: 'Ocean Pant',
      slug: 'Ocean Pant',
      image: '/images/p6.png',
      brand: 'JungMaven',
      category: 'Pant',
      description: 'An easy to wear, pull-on pant with slouchy wide legs',
      price: 50,
      countInStock: 10,
      rating: 5,
      numReviews: 30,
    },
    {
      //_id: '7',
      name: 'Megar Jean(Black)',
      slug: 'Megar Jean(Black)',
      image: '/images/p7.png',
      brand: 'Megar',
      category: 'Pant',
      description: 'high quality product',
      price: 60,
      countInStock: 10,
      rating: 5,
      numReviews: 30,
    },
    {
      //_id: '8',
      name: 'Megar Jean(Blue)',
      slug: 'Megar Jean(Blue)',
      image: '/images/p8.png',
      brand: 'Megar',
      category: 'Pant',
      description: 'high quality product',
      price: 60,
      countInStock: 10,
      rating: 5,
      numReviews: 30,
    },
  ],
};
export default data;
