const data = {
  products: [
    {
      name: 'cool mouse',
      slug: 'nike slim slug',
      category: '2hou',
      image: '/images/p1.png',
      price: 420,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'cool mouse',
      slug: 'nike slim slug',
      category: '2hou',
      image: '/images/p1.png',
      price: 420,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'cool mouse',
      slug: 'nike slim slug',
      category: '2hou',
      image: '/images/p1.png',
      price: 420,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'cool mouse',
      slug: 'nike slim slug',
      category: '2hou',
      image: '/images/p1.png',
      price: 420,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
