const data = {
  products: [
    {
      name: 'cool mouse',
      slug: 'a mouse',
      category: '2hou',
      image: '/images/p1.png',
      price: 420,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'padoru mouse',
      slug: 'b mouse',
      category: '2hou',
      image: '/images/p2.png',
      price: 69,
      countInStock: 10,
      brand: '2hou',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'cool mouse',
      slug: 'c mouse',
      category: '2hou',
      image: '/images/p1.png',
      price: 420,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'padoru mouse',
      slug: 'd mouse',
      category: '2hou',
      image: '/images/p2.png',
      price: 69,
      countInStock: 10,
      brand: '2hou',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
